### ISSUE TITLE
Exception switching from v.0.2.1 to 0.4.0

### ISSUE THREAD

**Issue by TBuc** [RadicalZephyr/boot-junit#8]
Hi,

when switching a project from boot-junit v.0.2.1 to v.0.4.0, the _test_ task fails preemptively throwing an exception. The test task is standard:
```
(deftask test
  "Compile and run jUnit tests."
  []
  (comp (javac)
        (junit)))

```
The current latest version of the project (commit hash: ee160d5), available at:
https://github.com/alda-lang/alda-client-java.git
works fine with boot-junit v.0.2.1. When just switching to v.0.4.0, it raises the following error when running _boot test_:

```
Compiling 49 Java source files...
Could not load class: java.alda.integrationtests.AldaClientTest...
                              java.lang.Thread.run              Thread.java:  748
java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  624
 java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1149
               java.util.concurrent.FutureTask.run          FutureTask.java:  266
                                               ...                               
               clojure.core/binding-conveyor-fn/fn                 core.clj: 1938
                                 boot.core/boot/fn                 core.clj: 1031
                               boot.core/run-tasks                 core.clj: 1021
                    boot.task.built-in/fn/fn/fn/fn             built_in.clj:  804
         radicalzephyr.boot-junit/eval286/fn/fn/fn           boot_junit.clj:   60
                              clojure.core/ex-info                 core.clj: 4617
clojure.lang.ExceptionInfo: Some tests failed or errored
clojure.lang.ExceptionInfo: Some tests failed or errored
    line: 100
```
when running other tasks that don't involve tests, everything keeps working fine.
Any ideas?
Thanks much.

**Comment by RadicalZephyr** [comment]
Thanks for the clear repro steps!

It looks like the issue is that your test classes are under `test/java` but you put `test` into the `:source-paths`.  Since your test packages don't include `java` at the beginning, these classes aren't being found when the clojure class loader tries to load them.  This is actually correct, since the package root isn't on the classpath.

Frankly, I'm more mystified as to why this _used_ to work under 0.2.1!  I suspect it's because the `reflections` library I was using is a bit too smart for it's own good.

Anyhow, I was able to run the tests successfully by changing the `:source-paths` to be:
``` clojure
  :source-paths #{"src" "test/java"}
```

This puts the package root directory on the classpath as it should be.

You could also get rid of the `java` directory and that should work too.

**Comment by RadicalZephyr** [comment]
ohh, I see what's happening.  I find the class names to run based on the `.class` extension, and then assume that the path name corresponds to the package name, which in this case is incorrect.  Notice that the error messages you are reporting show the class that is failing to load as having `java` as the first segment of the package name.  I guess this qualifies as a bug, but since there is an easy workaround, and jUnit 5 now offers a test discovery API (which I'll be [moving to eventually](#9)) I'm not going to do anything to fix this directly.
